version: "3.8"
services:
  php:
    build:
      context: .
      target: php
      args: 
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    ports:
      - 8000:8000
    depends_on:
      - database
  database:
    image: mysql:8.0
    ports:
        - 3306:3306
    environment:
        - MYSQL_DATABASE=mydb
        - MYSQL_ROOT_PASSWORD=secret
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: secret
  